### ISSUE TITLE
Corrigir tamanho do logo no menu

### ISSUE THREAD

**Issue by Ronicley** [FeelCodeTeam/site-feelcode#4]
## **Contexto**

O contexto do procedimento relatado são os conteúdos presentes em:
- Seção 'Menu': Diminuir o tamanho da logo.
- Seção 'Slogan': Diminuir o tamanho da fonte
- Geral:  O site todo em si, não fica agradável em um celular com tela pequena (testei em um iphone 5).

![image](https://user-images.githubusercontent.com/25643288/30516914-2b559b00-9b23-11e7-82ca-5fee064481cc.png) 
Não sei o modelo do iphone, por isso nao coloquei a resolução. Elas variam de modelo 

**Resolução 1650x1050**
![image](https://user-images.githubusercontent.com/25643288/30516935-ee37050a-9b23-11e7-9b21-441d31a5a8de.png)

**Resolução FullHD**
![image](https://user-images.githubusercontent.com/25643288/30516954-5a7ca116-9b24-11e7-9cdb-e820ce39974c.png)

## **Resultado esperado**
Uma aparência melhor para o site e um enquadramento legal em qualquer resolução.

**Comment by AlexandreKavalerski** [comment]
**Realizando alterações necessárias.** 
> O branch iss4 será criado e terá o commit 8fc3253ce2511d96d020c5d2e0ec1c0303cdbe95 como pai

**Comment by AlexandreKavalerski** [comment]
### Alterações realizadas!

- Tamanho do logo reduzido
- Tamanho do texto do cabeçalho alterado para que fique responsivo
- Melhor definição do grid para os cards da seção "O que fazemos" 

Alterações constam em: effc348  e 81b3e6c
